### PR TITLE
prevent adding tree node for empty filepath segments

### LINKED ISSUE #18490: error: Cannot read properties of undefined (reading 'add')
#### System
| | |
|------------ | -------------|
|Platform | win32 10.0.26100  |
|Architecture | x64 |
|Application Version | 1.15.2 |
|Process | renderer |
#### Message
Cannot read properties of undefined (reading 'add')
#### Title
```
Unhandled error in event "will-deploy"
```

#### Context
```
gamemode = Cyberpunk 2077,extension_version = 0.11.4
```
#### Stack
```
TypeError: Cannot read properties of undefined (reading 'add')
    at E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar.unpacked\bundledPlugins\new-file-monitor\index.js:1:1733
    at Array.forEach (<anonymous>)
    at h (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar.unpacked\bundledPlugins\new-file-monitor\index.js:1:1542)
    at E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar.unpacked\bundledPlugins\new-file-monitor\index.js:1:2960
    at Array.forEach (<anonymous>)
    at E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar.unpacked\bundledPlugins\new-file-monitor\index.js:1:2947
    at Generator.next (<anonymous>)
    at E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar.unpacked\bundledPlugins\new-file-monitor\index.js:1:1266
    at Promise.cancellationExecute [as _execute] (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:406:9)
    at Promise._resolveFromExecutor (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:103:10)
    at s (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar.unpacked\bundledPlugins\new-file-monitor\index.js:1:1011)
    at E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar.unpacked\bundledPlugins\new-file-monitor\index.js:1:2875
    at Array.map (<anonymous>)
    at E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar.unpacked\bundledPlugins\new-file-monitor\index.js:1:2867
    at Generator.next (<anonymous>)

Reported from:
Error
    at showError (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\renderer.js:10054:202)
    at mApi.showErrorNotification (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\renderer.js:9002:52)
    at E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\renderer.js:9108:165
    at tryCatcher (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (E:\01 JOGOS\C P 2077 V\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:15:14)
```
 

 
 Reported by: jfghardwar

### LINKED ISSUE #18811: [BUG-ALPHA] - Creating Snapshots taking a VERY long time on Deployment in FO4
**Your Nexus Mods username**
ChemBoy1

**Describe the bug**
When deploying mods in FO4, the "Creating Snapshots" step takes a VERY long time to complete. I can see in my Task Manager that Vortex is writing to disk, so it is probably writing snapshots to the .json file. Just not sure why it takes so long. 

Image

This also prevents the user from changing the managed game until the snapshotting is completed. 

I let it run for more than an hour, and it never completed. The only way I was able to get out of this state was to downgrade Vortex to 1.15.2. After downgrade, the snapshotting was completed in a few seconds, with the identical mod list. 

Mod List for Reference:

Image

This is realated to the newfile-monitor extension: https://github.com/Nexus-Mods/extension-new-file-monitor/blob/6b5ea82f1dfe7ecab1c8152f70fd189aaa9ce505/src/index.ts

[vortex.log](https://github.com/user-attachments/files/23570569/vortex.log)

**To Reproduce**
1. Deploy mods in FO4.
2. See that "Creating Snapshots" step take a long time with no mods. And a MUCH longer times with only a few mods installed. 

**Expected behavior**
Snapshotting should not take more than a few seconds, as is observed in Vortex 1.15.2.

**Screenshots**

Image

**Platform (please complete the following information):**
 - OS: Windows 11 25H2
 - Vortex Version 1.16.0-ALPHA.2

**Additional context**
Downgrading to 1.15.2 seems to resolve this issue, so it must be introduced in the alpha.

### PR DESCRIPTION
**Pull request by IDCs**
fixes nexus-mods/vortex#18490
part of [#18811](https://github.com/Nexus-Mods/Vortex/issues/18811)

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -33,7 +37,8 @@ function addToTree(tree: ITree,
         };
       }
       tree = tree.directories[iter];
-      if (entry !== undefined) {
+      // Defensive check: ensure tree is defined before accessing owners
```
Comment (Sewer56) [inline src/index.ts]: I don't do TS, but if I'm reading this right, `tree.directories[iter]` is updated right in the block above when `tree.directories[iter] === undefined`.

Therefore `tree !== undefined` is always true by definition, given we just set the value.

Unless there's multithreading involved, but I doubt.

Comment (IDCs) [reply src/index.ts]: Ha, good point - I think I initially added the tree check and then realized it's actually empty segments that are causing the issue.

Comment (IDCs) [reply src/index.ts]: fixed

**Review by insomnious — APPROVED** [review]
